# Generated by Django 4.1.6 on 2023-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название статьи')),
                ('start_link', models.URLField(verbose_name='Первоначальная ссылка')),
                ('late_link', models.CharField(max_length=30, verbose_name='Сокращенная ссылка')),
            ],
        ),
    ]
