# Generated by Django 4.1.6 on 2023-02-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_link_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='late_link',
        ),
    ]
